name: publish
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          commit-ish: 'HEAD'
          skip-unshallow: true
      - name: Update version on files
        run: |
          sed -i 's/^mod_version=.*/mod_version=${{steps.tagger.outputs.tag}}/' gradle.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 5qk7awuC
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: ${{steps.tagger.outputs.tag}}
          github-generate-changelog: true
          github-prerelease: false
          github-commitish: main
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar

          name: Sneak/Sprint ${{steps.tagger.outputs.tag}}
          version: ${{steps.tagger.outputs.tag}}
          version-type: release
          changelog-file: CHANGELOG.*

          loaders: |
            fabric
          game-versions: |
            1.20.4
          game-version-filter: none
          dependencies: |
            cloth-config
          java: |
            17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail